server:
  port: 8182

spring:
  application:
    name: validacao-app

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-app:8761/eureka/ 
  instance:
    preferIpAddress: false 
