server:
  port: 8081 

spring:
  application:
    name: dns-server-app
  service-discovery-app: http://eureka-server-app:8761/eureka/apps

eureka:
  decoderName: JacksonJson
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false
    fetch-registry: false